set smartindent
set expandtab
set tabstop=2
set shiftwidth=2
set vb t_vb=
set ruler
set nohls
set incsearch
"set nowrap
:syntax enable
":set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [ASCII=\%03.3b]\ [HEX=\%02.2B]\ [POS=%04l,%04v][%p%%]\ [LEN=%L]
":set laststatus=2
au BufReadPost * if line("'\"") > 0 &&
  \ line("'\"") <= line("$") | exe "normal g'\"" | endif

autocmd FileType make setlocal noexpandtab

autocmd BufWritePre * :%s/\s\+$//e

" Tell vim to remember certain things when we exit
"  '10  :  marks will be remembered for up to 10 previously edited files
"  "100 :  will save up to 100 lines for each register
"  :20  :  up to 20 lines of command-line history will be remembered
"  %    :  saves and restores the buffer list
"  n... :  where to save the viminfo files
set viminfo='10,\"100,:20,%,n~/.viminfo

autocmd BufRead,BufNewFile *.launch setfiletype roslaunch
